### ISSUE TITLE
Why WebRTC?

### ISSUE THREAD

**Issue by IbrH** [geckosio/geckos.io#10]
Sorry for this question in case the answer is obvious, but if the client connects directly to server and server then knows the IP, then why is WebRTC made use of?

**Comment by yandeu** [comment]
You mean why not simply use http post and get requests instead of establishing a complex WebRTC connection?

Because http runs on top of TCP, and WebRTC on top of UDP. UDP is much much faster and is normally used for Desktop Multiplayer Games. This is why geckos.io uses WebRTC. This is the whole idea of this library, to run fast.

See [this image](https://miro.medium.com/max/1675/0*usnfeQYk2Orx2-xv.).

Does this answer your question? :)

**Comment by IbrH** [comment]
yes, thanks
