### ISSUE TITLE
onDisconnect firing twice

### ISSUE THREAD

**Issue by KingCosmic** [geckosio/geckos.io#14]
as the title suggest, I'm having a issue where my disconnect callback fires twice

**Comment by yandeu** [comment]
Can you post a simplified snippet of your code?

**Comment by KingCosmic** [comment]
```js
const geckos = require('@geckos.io/server').default
const http = require('http')
const express = require('express')
const app = express()
const server = http.createServer(app)
const io = geckos()

io.addServer(server)
io.onConnection((channel) => {
  console.log('a user connected');

  entities[channel.id] = new Player(channel.id, world);

  channel.emit('initial-data', generateWorldState(false));

  channel.on('move', (input) => {
    input.player_id = channel.id;
    unprocessedInput.push(input)
  })

  channel.onDisconnect(() => {
    // this had to be added to make sure my server didnt crash on the second disconnect
    if (!entities[channel.id]) return;

    world.destroyBody(entities[channel._id].body);
    delete entities[channel.id];
  })
});

server.listen(4000, function () {
  console.log('listening on *:4000');
});```

**Comment by yandeu** [comment]
I checked it. You are right, there are 2 onDisconnect events.

This is because the WebRTC connectionState sends 2 signals, "failed" and "closed". In both cases, geckos emits the onDisconnect event.

There is also a third state called "disconnected", which also calls onDisconnect.

I propose to pass the connectionState along the onDisconnect event like so
```ts
channel.onDisconnect((event) => {
  if(event === 'closed') destroyBody()
  if(event === 'failed') console.log('something failed and I do not know what to do')
})
```
What do you think?

---

You will find more about the [connectionState here](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/connectionState).
Please also take a [look at this](https://github.com/geckosio/geckos.io/issues/4).

**Comment by KingCosmic** [comment]
I took a look at #4 but determined it wasn't the issue I was having the fix you suggested looks like it'll come in handy

**Comment by yandeu** [comment]
I added the changes to v1.3.0.

Also I finally finished the implementation of reliable messages.
