### ISSUE TITLE
[Question] React Native Compatibility

### ISSUE THREAD

**Issue by dngconsulting** [geckosio/geckos.io#21]
Hello, 

Do you know if geckos.io is compatible with React Native ? Is there anything that would prevent geckos.io to work with RN ?

Thank you for your answer

Sami

**Comment by yandeu** [comment]
I guess not by default. Geckos.io uses the WebRTC Web API. I believe RN has not included it.

But I found the package [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc), which uses the same API. It has a method called [registerGlobals()](https://github.com/react-native-webrtc/react-native-webrtc#registerglobals), which sets some global variables. It could very possibly be that @geckos.io/client works with this packages, since @geckos.io/client is a very small package and uses only standard API's.

Do you have the possibility to test it?

---
Why do you want to use geckos.io with RN anyway? Are you building a multiplayer game in RN?

**Comment by dngconsulting** [comment]
Thanks a lot for this answer. Yes we plan to use Geckos.io for a multiplayer innovative game. I really wanted to use UDP and as you know, there is no native UDP support in Browsers. Bridging WebRTC (which is complex) with a basic pub/sub middleware is just brillant. The benchmarks we made was excellent (we broadcast BLE events to the game engine, synchronization is an absolute necessity).

Sami
PS : The RN app is because we need this BLE connection. Smartphones are more suitable for that. But after digging around Bluetooth Web Api, looks like a simple html page using geckos.io would fit our needs.... if you have any suggestion...

**Comment by yandeu** [comment]
Is BLE Bluetooth Low Energy? If yes, maybe you could use [cordova](https://cordova.apache.org/) or [capacitor](https://capacitor.ionicframework.com/) (version 2 just came out) with the [BLE Plugin](https://ionicframework.com/docs/native/ble) instead of RN?

**Comment by yandeu** [comment]
I'm closing this issue. 
Once finished, I would be happy to see your game in the "[Who is using geckos.io](https://github.com/geckosio/geckos.io#who-is-using-geckosio)" section.
