### ISSUE TITLE
In the comparison table, why peer.js for non-authoritative game server?

### ISSUE THREAD

**Issue by bennlich** [geckosio/geckos.io#39]
Just curious, in [this table](https://github.com/geckosio/geckos.io#when-to-use-socketio-geckosio-or-peerjs), why do you recommend peer.js over geckos for a non-authoritative game server?

**Comment by yandeu** [comment]
I can't remember :smile: (This table is old)

You can of course use geckos.io in any of those cases.

I guess you should only use socket.io over geckos.io if you do not know how to deploy your own server and to forward the necessary ports. For instance if you want to use Heroku, then your only option is socket.io since the Node.js WebRTC implementation can't work on services like Heroku. 

I think I should update the table.

**Comment by bennlich** [comment]
Ah, k. Gotcha :) I'll let you close this or use as a reminder to update the table.

I think I'm going to try using geckos shortly! I'm excited.

**Comment by jdspugh** [comment]
A central server can act as a "judge" (authority) to give the final word on scores, game states, etc. Peer-to-peer (peerjs) games don't rely on a central authority (non-authoritative) and need to vote between themselves to decide on mutual outcomes.
