### ISSUE TITLE
onDisconnect is not called or gets called with delay

### ISSUE THREAD

**Issue by speekadievs** [geckosio/geckos.io#4]
Hey, I noticed an issue with the onDisconnect method. Whenever I close the connection (by refreshing the page or closing the browser), the onDisconnect method should be called on a server, but it doesn't or if it does, it does it with a delay (like 3-5 seconds). 

This is a pretty big issue, as I've created a room handler which automatically destroys the information about the room whenever the last channel disconnects, but now for example after refreshing the page, the room isn't cleared and the user just connects right back to the same room.

**Comment by yandeu** [comment]
I guess the delay is normal since the server has to check if the client reconnects within a few seconds or not, to keep the connection open. 

In **connectionsManager.ts** I listen for the **onconnectionstatechange**. If the result is **disconnected** it closes the connection. That is why I can't make it faster.
```ts
const pc = connection.peerConnection

pc.onconnectionstatechange = () => {
  if (pc.connectionState === 'disconnected') {
    connection.channel.eventEmitter.emit(EVENTS.DISCONNECT)
    this.deleteConnection(connection)
  }
}
```
But I noticed that someting the result is **failed** if the client closes or reloads the window. So I guess I should change one line to
```ts
if (pc.connectionState === 'disconnected' || pc.connectionState === 'failed') {
```
---
But I see your issue. A new client connects, sees that there is a player in the room XY and connects to it, even though the other player left 2 seconds ago :/

**Comment by speekadievs** [comment]
I think I could use the delay to my advantage and just restore the player state if for some reason his connection drops for a few seconds (accidental CTRL+R for example).

But it would be great if you could change the line in connectionsManager. I believe there's also a `closed` state, so maybe you should listen to that too?

**Comment by speekadievs** [comment]
@yandeu I created a PR for the failed state check https://github.com/geckosio/geckos.io/pull/5

**Comment by yandeu** [comment]
I just added it to npm.

**Comment by speekadievs** [comment]
Great, tested it and looks like it works now. The delay is still there, but at least now it closes the connection every time.

Closing this
