### ISSUE TITLE
has geckos.io ever been stress tested?

### ISSUE THREAD

**Issue by m0dE** [geckosio/geckos.io#68]
I'm curious about how feasible for me to make 32+ player multiplayer game using geckos.io.
I heard that WRTC doesn't scale very well with player count, but I'd happily be proven wrong.
Are there any games in production that's using geckos.io that I can play?
Also, @yandeu I sent you an email a few days ago. Did you receive it?

**Comment by OrlandoLuque** [comment]
I am in the same boat!

I would as well implement load balancing as well, but intra-server communications could be done with dgram.

Anyway I have to test more as a ping pong with geckos got slightly better trimming than dgram. Around 2ms each. But I have only spam messages with geckos, getting like 300.000 packets in a second with a message of around 50 bytes, but I do not yet if u got better results than it should maybe because the packages are being discarded after the send or receiving buffers are filled.

Do you know how to implement the buffers by chance?

Of you can send, saying a number, 100k packages per second... That could feed a ton of players.

My project is yet quite green, I am pretty busy with other things. Will try to do some more testing later.

**Comment by OrlandoLuque** [comment]
I observed a overhead of several bytes as well, maybe because of the used channel name (like “chat message”), but I have to check it again change the name, etc.

Wireshark filtering is not intuitive at all...

**Comment by OrlandoLuque** [comment]
If multiple connections impacts too much the performance, maybe it is an issue of the hash or dictionary used to identify the client.

**Comment by yandeu** [comment]
I made a repository for a [stress test](https://github.com/geckosio/stress-test).

The DataChannels do have a overhead of about 50-70 bytes.

What are the results of your tests?

**Comment by jdspugh** [comment]
I'm making a game, Galactic Battle, using geckos.io. You can try it out at http://galactic-battle.com. Should support many players but I haven't stress tested yet. Feedback welcome.

**Comment by OrlandoLuque** [comment]
Sorry, I am pretty busy with a 5 years ond and 6 months old children :-)

I have just downloaded a checked a bit. As I am a noob I am still seeing how you are sending the data, as I was using channel.emit of your original example.

In my computer, each tick is taking 66 to 75 milliseconds.

I tried reducing the time interval so to have 20 network updates per second (I read that it was common to do 60 game ticks and 20 network ticks per second, while predicting in the client side) but the tick interval is still not reduced. Mysterious!

With my emit benchmark, I saw that I could send 300.000 packets per second because, if you send a few the code takes around 2 milliseconds to send the package, when you send too many, it is faster. Maybe it is just that he is gathering several packages in each physical network shipment? (like Zero MQ does?). I will try to check with Wireshark.

I opened several duplicates of the page and it still did not lose many FPS either.

About the overhead (not overheat?), I had seen less than that while using emit, but I will try to check it again today, as those tests were like 1 month ago and I do not remember much.

**Comment by OrlandoLuque** [comment]
hmm, I used a different way to take the spent time. I do not know why, but when I got your code into webstorm, it was not including as a library the node core libraries. Lol.

If it weird, because then I only set 20 ticks per second, each tick is faster.

60 ticks (the default):
![image](https://user-images.githubusercontent.com/11312932/101358498-39753100-389b-11eb-881d-4b7a86345843.png)

20 ticks:
![image](https://user-images.githubusercontent.com/11312932/101358334-ff0b9400-389a-11eb-8b18-516901f60cd8.png)

The modification is just...
`setInterval(() => {
  let hs = process.hrtime();

  const u = [...updates]
  updates = []

  const buffer = new ArrayBuffer(u.length * 8)
  const view = new DataView(buffer)

  for (let i = 0; i < u.length; i++) {
    view.setInt32(i * 8, u[i].x)
    view.setInt32(i * 8 + 4, u[i].y)
  }

  io.raw.emit(buffer)

  let end = new Date().getTime()

  const realFps = Math.round(FPS - (end - start))
  if (realFps < -2) console.log(realFps)


  let hr = process.hrtime(hs);
  process.stdout.clearLine();
  console.log('[' + hr[0] + 's ' + hr[1] / 1000000 + 'ms] of ' + FPS + ' milliseconds per tick');

  start = end
}, FPS)`

**Comment by OrlandoLuque** [comment]
> I guess a node.js cluster would help, but for now, geckos.io does not work in a cluster.
What do you mean?

I was planning to allow several node processes to share the workload.

The idea is:
* use my own algorithm (which could work as a quadtree with some parameters if you prefer so) to index the players and other objects to the "map".
* one load-balancing node. Use the same algorithm to manage only players.  It will divide or join the map areas as the workload of the nodes is higher or lower (or player count?).
* node player and objects data in an area control being transferred to another node will be sent to that node as well.
* a node will send the data of things to a neighboring node when those things happen close to the frontier between nodes.
* when a player is transferred to a different node, the player packets will be sent to the new node port. 

That is my initial idea, and my lack of experience means it could be done better.

**Comment by OrlandoLuque** [comment]
Checking with wireshark... and using emit, I see an overheat of 67 and 139 bytes per packet.
(I have been sending 50 bytes string messages)
![image](https://user-images.githubusercontent.com/11312932/101549504-17200800-39ae-11eb-98be-cd94073cd329.png)
This is a bit insane. grrr

**Comment by OrlandoLuque** [comment]
I have seen as well several enormous packets like:
![image](https://user-images.githubusercontent.com/11312932/101549680-5ea69400-39ae-11eb-9b1f-2166d306ac99.png)

But it is in a different port, so maybe it is a different application sending packages?


And... dunno why... it is not using the specified port 3000...
![image](https://user-images.githubusercontent.com/11312932/101549802-96154080-39ae-11eb-9023-ca8f9fb53823.png)

**Comment by OrlandoLuque** [comment]
Hmmm, I see a DUST package.

Are you supporting all the webrtc protocols? :-)
![image](https://user-images.githubusercontent.com/11312932/101549920-c8bf3900-39ae-11eb-8889-f176eb89e838.png)

**Comment by OrlandoLuque** [comment]
If I emit to c instead of "chat message", the 189 goes down up to 177. The 117 is still the same.

![image](https://user-images.githubusercontent.com/11312932/101550521-bc87ab80-39af-11eb-87b3-21569b02c1d4.png)

And if on top of that I increases the message from 50 to 200...
![image](https://user-images.githubusercontent.com/11312932/101550703-15efda80-39b0-11eb-9594-df12a23b4bdc.png)
only the 177 goes up to 325. So I guess the 117 long package is maybe an ACK???

**Comment by RaggarDK** [comment]
Someone made me aware of the following issue: https://github.com/node-webrtc/node-webrtc/issues/648
Testing Geckos locally on my rig, sending messages to 20 peers takes 80-110+ms. Independent of message-length.

 I would strongly suggest @yandeu to replace the current big, bloated and slow implementation of WebRTC with node-datachannel
https://github.com/murat-dogan/node-datachannel

It is lightweight and in testing only takes 1-2ms to message 30 peers.

**Comment by yandeu** [comment]
I've been looking for a long time for a better WebRTC implementation. I will test [murat-dogan/node-datachannel](https://github.com/murat-dogan/node-datachannel).

**Comment by yandeu** [comment]
Looks like it works. I will work on a new branch to implement it. Hopefully, it is worth the time.

**Comment by yandeu** [comment]
I have started implementing [node-datachannel](https://www.npmjs.com/package/node-datachannel) today. There are already 8 of 12 tests passing:
```console
Test Suites: 4 failed, 8 passed, 12 total
````
You can follow the development process in the [v2 branch](https://github.com/geckosio/geckos.io/tree/v2).

**Comment by yandeu** [comment]
I've already made some comparisons:

| | node-datachannel | node-wrtc |
| --- | --- | --- |
| 100 messages to 1 client | 6ms | 25ms |
| 10 messages to 10 clients | 6ms | 34ms |
| 100 messages to 10 clients | 59ms | 274ms |

**Comment by OrlandoLuque** [comment]
Cool!!!

What about the messages' length overheat??

**Comment by m0dE** [comment]
@yandeu thanks for the table. How about 10 messages to 100 clients?

**Comment by yandeu** [comment]
> What about the messages' length overheat??

> How about 10 messages to 100 clients?

I don't know. Maybe you can test it?

```console
npm i @geckos.io/client@dev @geckos.io/server@dev
```
